### PR TITLE
Upgrade to v1.4.2

### PR DESCRIPTION
**Pull request by tituspijean**
## PR Status

- [x] Code finished and ready to be reviewed/tested
- [x] The fix/enhancement were manually tested (if applicable)

## Automatic tests

Automatic tests can be triggered on https://ci-apps-dev.yunohost.org/ *after creating the PR*, by commenting "!testme", "!gogogadgetoci" or "By the power of systemd, I invoke The Great App CI to test this Pull Request!". (N.B. : for this to work you need to be a member of the Yunohost-Apps organization)

### CODE REVIEW

**Comment by tituspijean** [comment]
!testme

**Comment by tituspijean** [comment]
Should we make a call for testers?

**Comment by OniriCorpe** [comment]
we can ask on the forum
i personally don't use this app, btw

**Comment by ericgaspar** [comment]
The best branch for testing is master branch 😅

**Review by alexAubin — APPROVED** [review]

**Comment by tituspijean** [comment]
and wait for all this to blow over

**Pull request merged**
